server:
  port: ${server-port}
  servlet:
    context-path: /api
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${jwt-issuer-uri}
  datasource:
    url: ${database-url}/${database-name}
    username: ${database-username}
    password: ${database-password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations:
      - classpath:/schema.sql
      continue-on-error: true
  jpa:
    show-sql: ${show-sql}       
    hibernate:
      ddl-auto: ${ddl-auto}
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher 
  rabbitmq:
    template:
      default-receive-queue: ${rabbitmq-default-queue}
      exchange: ${rabbitmq-default-exchange}
      routing-key: ${rabbitmq-default-routekey}
e-commerce:
  application:
    tax-percentage: ${application-tax-percentage}
    transaction-url: ${transaction-url}
    client-id: ${client-id}
    